"use client";

import { useEffect, useState } from "react";
import { BookOpen, LogOut, Pencil, Save, ScanSearch, ShieldCheck } from "lucide-react";
import { signOut, updateProfile } from "firebase/auth";
import Header from "@/app/components/Header";
import BottomNav from "@/app/components/BottomNav";
import { useUser } from "@/app/context/UserContext";
import { auth } from "@/lib/firebase";
import { subscribeLearningProfile, updateUserProfile, type LearningProfile } from "@/lib/firestore";

export default function ProfilePage() {
  const { user } = useUser(); const [profile, setProfile] = useState<LearningProfile>({}); const [name, setName] = useState(""); const [editing, setEditing] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  useEffect(() => { if (user) return subscribeLearningProfile(user.uid, setProfile); }, [user]);
  async function saveName() { const nextName = name.trim() || user?.fullName || "User"; if (!user) return; setSaving(true); setError(""); try { if (auth.currentUser) await updateProfile(auth.currentUser, { displayName: nextName }); await updateUserProfile(user.uid, { fullName: nextName }); setEditing(false); } catch { setError("We could not save your profile. Please try again."); } finally { setSaving(false); } }
  const displayName = user?.fullName || "Guidr user"; const initial = (displayName || user?.email || "U").trim().charAt(0).toUpperCase(); const stats = [{ label: "Scans", value: profile.casesScanned || 0, icon: ScanSearch }, { label: "Lessons", value: profile.articlesRead?.length || 0, icon: BookOpen }, { label: "XP", value: profile.xp || 0, icon: ShieldCheck }];
  return <div className="guidr-container"><Header /><main className="flex-1 overflow-y-auto no-scrollbar px-4 py-5 pb-safe"><div className="mx-auto flex max-w-2xl flex-col gap-5"><section className="flex flex-col items-center rounded-2xl border border-gray-100 bg-white p-6 shadow-sm"><div className="flex size-20 items-center justify-center rounded-full bg-guidr-primary text-3xl font-bold text-white">{initial}</div>{editing ? <div className="mt-4 flex w-full max-w-sm gap-2"><input autoFocus value={name || displayName} onChange={(event) => setName(event.target.value)} className="min-w-0 flex-1 rounded-xl border border-gray-200 px-3 py-2 text-center text-sm outline-none focus:border-guidr-primary" /><button disabled={saving} onClick={saveName} className="rounded-xl bg-guidr-primary px-3 text-white"><Save size={18} /></button></div> : <div className="mt-3 flex items-center gap-2"><h1 className="text-xl font-bold text-guidr-text">{displayName}</h1><button aria-label="Edit name" onClick={() => { setName(displayName); setEditing(true); }} className="rounded-lg p-1 text-guidr-primary hover:bg-guidr-primary-light"><Pencil size={16} /></button></div>}<p className="mt-1 text-sm text-guidr-muted">{user?.email || "Signed-in user"}</p>{error && <p role="alert" className="mt-3 text-xs text-guidr-red">{error}</p>}</section><section className="grid grid-cols-3 divide-x divide-gray-100 overflow-hidden rounded-2xl border border-gray-100 bg-white shadow-sm">{stats.map(({ label, value, icon: Icon }) => <div key={label} className="flex flex-col items-center gap-1 py-4"><Icon size={18} className="text-guidr-primary" /><strong className="text-lg text-guidr-text">{value}</strong><span className="text-xs text-guidr-muted">{label}</span></div>)}</section><section className="rounded-2xl border border-gray-100 bg-white p-5 shadow-sm"><h2 className="font-bold text-guidr-text">Your account</h2><p className="mt-2 text-sm leading-6 text-guidr-muted">Your saved learning progress and scan history are tied to this account. Keep your sign-in secure and never share verification codes.</p></section><a href="tel:997" className="flex items-center gap-3 rounded-2xl border border-red-100 bg-guidr-red-light p-4 text-left"><ShieldCheck className="text-guidr-red" /><span><strong className="block text-sm text-guidr-text">Need urgent scam help?</strong><span className="text-xs text-guidr-muted">Call NSRC 997 if money was transferred.</span></span></a><button onClick={() => signOut(auth)} className="flex w-full items-center justify-center gap-2 rounded-2xl border border-red-100 bg-white py-3.5 font-semibold text-guidr-red hover:bg-guidr-red-light"><LogOut size={18} />Sign out</button></div></main><BottomNav /></div>;
}