export type LearnArticle = { id: string; title: string; category: string; minutes: number; xp: number; summary: string; points: string[] };

export const LEARN_ARTICLES: LearnArticle[] = [
  { id: "phishing-red-flags", title: "Three red flags in phishing messages", category: "Phishing", minutes: 3, xp: 25, summary: "Urgency, unfamiliar links, and requests for credentials are the classic warning signs.", points: ["Pause when a message threatens a deadline or account closure.", "Open your bank or service from its official app instead of using the message link.", "Never share a password, PIN, or OTP with another person."] },
  { id: "otp-safety", title: "Why your OTP must stay private", category: "Phishing", minutes: 2, xp: 25, summary: "A one-time password approves an action as you. Banks will not ask you to read it aloud.", points: ["Enter an OTP only in the app or site you opened yourself.", "End the call if someone asks you for a code.", "Contact the institution through an official number if you are worried."] },
  { id: "parcel-scams", title: "How parcel scams work", category: "Delivery Scam", minutes: 3, xp: 25, summary: "A small delivery fee is bait for a cloned payment page and your card details.", points: ["Check a tracking number in the courier's official app or website.", "Do not pay a fee through an unexpected SMS link.", "Treat shortened or misspelled courier domains as unsafe."] },
  { id: "job-task-scams", title: "Spot an easy-task job scam", category: "Job Scam", minutes: 3, xp: 25, summary: "A promised commission becomes a request to top up money that you cannot withdraw.", points: ["A legitimate employer never makes you pay to start working.", "Verify the company using its official website and SSM details.", "Leave chats that pressure you to transfer or recruit others."] },
  { id: "investment-scams", title: "Guaranteed returns are not investments", category: "Investment Scam", minutes: 4, xp: 30, summary: "High guaranteed returns, urgency, and private chat groups are strong signs of investment fraud.", points: ["No investment can promise high returns without risk.", "Check licences and investor alerts before sending money.", "Do not send funds or crypto to a stranger who contacted you first."] },
  { id: "impersonation-calls", title: "Fake police, bank, and agency calls", category: "Impersonation", minutes: 3, xp: 25, summary: "Scammers use authority and fear to push victims into moving money to a so-called safe account.", points: ["Government agencies and banks do not demand secret emergency transfers.", "Hang up and call the public number you find independently.", "If money has been sent, call NSRC at 997 immediately."] },
];

export const DAILY_CHALLENGE = { message: "Hi! Earn RM300 a day liking videos from home. Top up RM50 to activate your earning account.", answer: "scam" as const, explanation: "Real employers do not require an upfront payment to let you work or withdraw earnings.", xp: 20 };

export function todayKey(date = new Date()) { return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`; }